## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np

In [3]:
mat1 =[[0, 1, 4], [2, 3, 5], [4, 5, 7]]
mat2 = [[1, 2, 3], [3, 4, 5], [5, 6, 0]]
x= np.array(mat1)
y= np. array(mat2)
multiplication=np.dot(x, y)
print(multiplication)

[[23 28  5]
 [36 46 21]
 [54 70 37]]


## Write a NumPy program to compute the determinant of a given square array

In [ ]:
from numpy import linalg as LA

In [8]:
sq=np.array([
    [3, 5, 7],
    [2, 7, 9],
    [2, 6, 7]
])
print (sq)
print (np.linalg.det(sq))

[[3 5 7]
 [2 7 9]
 [2 6 7]]
-8.999999999999998


## Write a NumPy program to compute the cross product of two given vectors

In [9]:
cross=np.cross(x, y)
print(cross)

[[ -5   4  -1]
 [ -5   5  -1]
 [-42  35  -1]]


## Write a NumPy program to compute the condition number of a given matrix

In [10]:
condition=LA.cond(sq)
print (condition)

41.52812222958721


## Write a NumPy program to compute the inverse of a given matrix

In [11]:
inverse=LA.inv(sq)
print (inverse)

[[ 0.55555556 -0.77777778  0.44444444]
 [-0.44444444 -0.77777778  1.44444444]
 [ 0.22222222  0.88888889 -1.22222222]]
